homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include misc/customize.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_key_path


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
introduction:

history:

logger:
  default: info
  logs:
    homeassistant.components.zwave: info

recorder:
  purge_keep_days: 7

#Logbook
logbook:
  include:
    domains:
      - sensor
# Text to speech
tts:
  - platform: google

sun:

discovery:

#upnp:
#  port_mapping: false

#MQTT
mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

#Netatmo
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
  discovery: false

#Zwave
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_secret_key
  device_config: !include zwave_device_config.yaml

#RfxCom
rfxtrx:
  device: /dev/ttyUSB0

###########INCLUDES#####
alert: !include_dir_merge_named alerts/
input_boolean: !include misc/input_boolean.yaml
input_number: !include misc/input_number.yaml
input_select: !include misc/input_select.yaml
binary_sensor: !include_dir_list binary_sensors/
sensor: !include_dir_list sensors/
group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named scripts/
zone: !include_dir_list zones/
weather: !include_dir_list weather/
climate: !include_dir_list climate/
